services:
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "32200:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=almacen2
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  usuarios:
    build: ./microservicios/Usuarios
    container_name: usuarios
    ports:
      - "3001:3001"
    depends_on:
      - db

  productos:
    build: ./microservicios/Productos
    container_name: productos
    ports:
      - "3002:3002"
    depends_on:
      - db

  ordenes:
    build: ./microservicios/Ordenes
    container_name: ordenes
    ports:
      - "3003:3003"
    depends_on:
      - db
      - usuarios
      - productos

  microweb:
    build: ./microWeb
    container_name: microweb
    ports:
      - "3080:80"
    depends_on:
      - usuarios
      - productos
