version: '3'
services:
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "32200:3306"
    environment:
      - MYSQL_ROOT_PASSWORD: root
      - MYSQL_DATABASE: almacen2
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  usuarios:
    build: ./microservicios/Usuarios
    links: 
      - db
    ports:
      - "3001:3001"
   

  productos:
    build: ./microservicios/Productos
    links: 
      - db
    ports:
      - "3002:3002"
  

  ordenes:
    build: ./microservicios/Ordenes
    links: 
      - db
    ports:
      - "3003:3003"
    links: 
      - db
    

  microweb:
    build: ./microWeb
    links:
      - usuarios
      - productos
      - ordenes
    ports:
      - "3080:80"
   
